#!/usr/bin/env bash
set -e
HDR="include/FontKit.h"
OUT="examples/autogen.c"

if [ ! -f "$HDR" ]; then
  echo "Header not found: $HDR"
  exit 1
fi

echo "Scanning $HDR for FontKit types and functions..."

# Collect candidate type tokens from typedef/declaration lines
types=$(grep -E 'typedef|struct|enum' "$HDR" | tr -s ' ' '\n' | grep -Eo '\b(FK_[A-Za-z0-9_]+|[a-z0-9_]+font_t|[a-z0-9_]+bitmap_t|FK_[A-Za-z0-9_]+Bitmap)\b' | sort -u)

# Collect fk_* functions
funcs=$(grep -oE '\b[fF][kK]_[A-Za-z0-9_]+' "$HDR" | sort -u)

echo
echo "Found candidate types:"
echo "$types" | nl -ba -w2 -s'. '
echo
echo "Found candidate functions (fk_*):"
echo "$funcs" | nl -ba -w2 -s'. '
echo

# heuristics: pick font type and bitmap type
font_type=$(echo "$types" | grep -E 'FK_[A-Za-z]*Font|[a-z0-9_]+font_t' | head -n1)
bitmap_type=$(echo "$types" | grep -Ei 'Bitmap|bitmap' | head -n1)

# heuristics: pick load, raster/render, write_ppm, free_font, free_bitmap, glyph index functions
load_fn=$(echo "$funcs" | grep -Ei 'load.*memory|load.*font|load_font' | head -n1)
render_fn=$(echo "$funcs" | grep -Ei 'raster|render|draw.*glyph' | head -n1)
glyph_index_fn=$(echo "$funcs" | grep -Ei 'glyph.*index|codepoint|get_glyph_index' | head -n1)
write_fn=$(echo "$funcs" | grep -Ei 'write_ppm|writeppm|write_ppm' | head -n1)
free_font_fn=$(echo "$funcs" | grep -Ei 'free_font|freefont' | head -n1)
free_bitmap_fn=$(echo "$funcs" | grep -Ei 'free_bitmap|freebitmap' | head -n1)

# Fallbacks for common names if detection failed
: ${font_type:=FK_Font}
: ${bitmap_type:=FK_Bitmap}
: ${load_fn:=fk_load_font_memory}
: ${render_fn:=fk_render_glyph}
: ${glyph_index_fn:=fk_glyph_index_for_codepoint}
: ${write_fn:=fk_write_ppm}
: ${free_font_fn:=fk_free_font}
: ${free_bitmap_fn:=fk_free_bitmap}

echo "Using:"
echo "  font type:        $font_type"
echo "  bitmap type:      $bitmap_type"
echo "  load function:    $load_fn"
echo "  glyph index fn:   $glyph_index_fn"
echo "  render function:  $render_fn"
echo "  write function:   $write_fn"
echo "  free font fn:     $free_font_fn"
echo "  free bitmap fn:   $free_bitmap_fn"
echo

cat > "$OUT" <<EOF
// This file was generated by scripts/generate_demo_from_header.sh
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "FontKit.h"

#define FONT_PATH "assets/fonts/truetype/Roboto-Regular.ttf"

int main(void){
    printf("FontKit auto-generated demo\\n\\n");

    FILE *f = fopen(FONT_PATH,"rb");
    if(!f){ fprintf(stderr, "Error opening %s\\n", FONT_PATH); return 1; }
    fseek(f,0,SEEK_END);
    long len = ftell(f);
    fseek(f,0,SEEK_SET);
    unsigned char *buf = malloc(len);
    if(!buf){ fclose(f); fprintf(stderr,"malloc failed\\n"); return 1; }
    fread(buf,1,len,f);
    fclose(f);

    $font_type *font = NULL;
    font = $load_fn(buf, (size_t)len);
    if(!font){
        fprintf(stderr, "Failed to load font using %s\\n", "$load_fn");
        free(buf);
        return 1;
    }

    int gi = -1;
    gi = $glyph_index_fn(font, (uint32_t)'A');
    if(gi < 0){
        fprintf(stderr, "Glyph index lookup failed for 'A'\\n");
        $free_font_fn(font);
        free(buf);
        return 1;
    }

    $bitmap_type bmp;
    if($render_fn(font, gi, 48.0f, 2, &bmp) == FK_OK){
        $write_fn("output_normal.ppm", &bmp);
        $free_bitmap_fn(&bmp);
        printf("Saved output_normal.ppm\\n");
    } else {
        fprintf(stderr, "Rendering failed (tried %s)\\n", "$render_fn");
    }

    $free_font_fn(font);
    free(buf);
    return 0;
}
EOF

echo "Wrote $OUT"
echo "Now build with: make demo (or compile examples/autogen.c with -Iinclude -Isrc)"
