// This file was generated by scripts/generate_demo_from_header.sh
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "FontKit.h"

#define FONT_PATH "assets/fonts/truetype/Roboto-Regular.ttf"

int main(void){
    printf("FontKit auto-generated demo\n\n");

    FILE *f = fopen(FONT_PATH,"rb");
    if(!f){ fprintf(stderr, "Error opening %s\n", FONT_PATH); return 1; }
    fseek(f,0,SEEK_END);
    long len = ftell(f);
    fseek(f,0,SEEK_SET);
    unsigned char *buf = malloc(len);
    if(!buf){ fclose(f); fprintf(stderr,"malloc failed\n"); return 1; }
    fread(buf,1,len,f);
    fclose(f);

    FK_Font *font = NULL;
    font = fk_load_font(buf, (size_t)len);
    if(!font){
        fprintf(stderr, "Failed to load font using %s\n", "fk_load_font");
        free(buf);
        return 1;
    }

    int gi = -1;
    gi = fk_glyph_index_for_codepoint(font, (uint32_t)'A');
    if(gi < 0){
        fprintf(stderr, "Glyph index lookup failed for 'A'\n");
        fk_free_font(font);
        free(buf);
        return 1;
    }

    FK_Bitmap bmp;
    if(FK_RenderOptions(font, gi, 48.0f, 2, &bmp) == FK_OK){
        fk_write_ppm("output_normal.ppm", &bmp);
        fk_free_bitmap(&bmp);
        printf("Saved output_normal.ppm\n");
    } else {
        fprintf(stderr, "Rendering failed (tried %s)\n", "FK_RenderOptions");
    }

    fk_free_font(font);
    free(buf);
    return 0;
}
